### ISSUE TITLE
Sounds a lot like DAPR

### ISSUE THREAD

**Issue by samcov** [mehdihadeli/MicroBootstrap#8]
It would be helpful if you had a block diagram overview, but it does sound like this is very much like Dapr.

If you know Dapr, could you comment on the differences.

**Comment by mehdihadeli** [comment]
Hi @samcov,
I have a plane for creating a complete documentation website with detail explanation about this project.
I didn't work with DAPR, but I've seen dapr docs and I can say they are very similar in most cases, but I want to add extra feature like handling kafka, azure services bus and every thing else that helpful in the future, DAPR is great also :)
